plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\pedro\\Downloads\\link-flow-limpo\\super-painel-desentupidoras"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Link = "</sitemap-index.xml>; rel=\"sitemap\", </llms.txt>; rel=\"llms-txt\", </robots.txt>; rel=\"robots\""